package hll.zpf.starttravel.common.database;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import hll.zpf.starttravel.common.database.entity.DetailWithMember;

import hll.zpf.starttravel.common.database.entity.Detail;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DETAIL".
*/
public class DetailDao extends AbstractDao<Detail, String> {

    public static final String TABLENAME = "DETAIL";

    /**
     * Properties of entity Detail.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "id");
        public final static Property Name = new Property(1, String.class, "name", false, "name");
        public final static Property Memo = new Property(2, String.class, "memo", false, "memo");
        public final static Property Date = new Property(3, String.class, "date", false, "date");
        public final static Property Money = new Property(4, float.class, "money", false, "money");
        public final static Property DetailTravelId = new Property(5, String.class, "detailTravelId", false, "travel_id");
    }

    private DaoSession daoSession;

    private Query<Detail> member_DetailListQuery;
    private Query<Detail> travel_DetailListQuery;

    public DetailDao(DaoConfig config) {
        super(config);
    }
    
    public DetailDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DETAIL\" (" + //
                "\"id\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"name\" TEXT," + // 1: name
                "\"memo\" TEXT," + // 2: memo
                "\"date\" TEXT," + // 3: date
                "\"money\" REAL NOT NULL ," + // 4: money
                "\"travel_id\" TEXT);"); // 5: detailTravelId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DETAIL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Detail entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String memo = entity.getMemo();
        if (memo != null) {
            stmt.bindString(3, memo);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(4, date);
        }
        stmt.bindDouble(5, entity.getMoney());
 
        String detailTravelId = entity.getDetailTravelId();
        if (detailTravelId != null) {
            stmt.bindString(6, detailTravelId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Detail entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String memo = entity.getMemo();
        if (memo != null) {
            stmt.bindString(3, memo);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(4, date);
        }
        stmt.bindDouble(5, entity.getMoney());
 
        String detailTravelId = entity.getDetailTravelId();
        if (detailTravelId != null) {
            stmt.bindString(6, detailTravelId);
        }
    }

    @Override
    protected final void attachEntity(Detail entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public Detail readEntity(Cursor cursor, int offset) {
        Detail entity = new Detail( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // memo
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // date
            cursor.getFloat(offset + 4), // money
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // detailTravelId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Detail entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMemo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDate(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMoney(cursor.getFloat(offset + 4));
        entity.setDetailTravelId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Detail entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(Detail entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Detail entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "detailList" to-many relationship of Member. */
    public List<Detail> _queryMember_DetailList(String memberId) {
        synchronized (this) {
            if (member_DetailListQuery == null) {
                QueryBuilder<Detail> queryBuilder = queryBuilder();
                queryBuilder.join(DetailWithMember.class, DetailWithMemberDao.Properties.DetailId)
                    .where(DetailWithMemberDao.Properties.MemberId.eq(memberId));
                member_DetailListQuery = queryBuilder.build();
            }
        }
        Query<Detail> query = member_DetailListQuery.forCurrentThread();
        query.setParameter(0, memberId);
        return query.list();
    }

    /** Internal query to resolve the "detailList" to-many relationship of Travel. */
    public List<Detail> _queryTravel_DetailList(String detailTravelId) {
        synchronized (this) {
            if (travel_DetailListQuery == null) {
                QueryBuilder<Detail> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.DetailTravelId.eq(null));
                travel_DetailListQuery = queryBuilder.build();
            }
        }
        Query<Detail> query = travel_DetailListQuery.forCurrentThread();
        query.setParameter(0, detailTravelId);
        return query.list();
    }

}
