package hll.zpf.starttravel.common.database;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import hll.zpf.starttravel.common.database.entity.Step;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STEP".
*/
public class StepDao extends AbstractDao<Step, String> {

    public static final String TABLENAME = "STEP";

    /**
     * Properties of entity Step.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "id");
        public final static Property Name = new Property(1, String.class, "name", false, "name");
        public final static Property Memo = new Property(2, String.class, "memo", false, "memo");
        public final static Property StartDate = new Property(3, String.class, "startDate", false, "start_date");
        public final static Property EndDate = new Property(4, String.class, "endDate", false, "end_date");
        public final static Property Latitude = new Property(5, float.class, "latitude", false, "latitude");
        public final static Property Longitude = new Property(6, int.class, "longitude", false, "longitude");
        public final static Property Image = new Property(7, byte[].class, "image", false, "image");
        public final static Property StepTravelId = new Property(8, String.class, "stepTravelId", false, "travel_id");
    }

    private Query<Step> travel_StepListQuery;

    public StepDao(DaoConfig config) {
        super(config);
    }
    
    public StepDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STEP\" (" + //
                "\"id\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"name\" TEXT," + // 1: name
                "\"memo\" TEXT," + // 2: memo
                "\"start_date\" TEXT," + // 3: startDate
                "\"end_date\" TEXT," + // 4: endDate
                "\"latitude\" REAL NOT NULL ," + // 5: latitude
                "\"longitude\" INTEGER NOT NULL ," + // 6: longitude
                "\"image\" BLOB," + // 7: image
                "\"travel_id\" TEXT);"); // 8: stepTravelId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STEP\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Step entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String memo = entity.getMemo();
        if (memo != null) {
            stmt.bindString(3, memo);
        }
 
        String startDate = entity.getStartDate();
        if (startDate != null) {
            stmt.bindString(4, startDate);
        }
 
        String endDate = entity.getEndDate();
        if (endDate != null) {
            stmt.bindString(5, endDate);
        }
        stmt.bindDouble(6, entity.getLatitude());
        stmt.bindLong(7, entity.getLongitude());
 
        byte[] image = entity.getImage();
        if (image != null) {
            stmt.bindBlob(8, image);
        }
 
        String stepTravelId = entity.getStepTravelId();
        if (stepTravelId != null) {
            stmt.bindString(9, stepTravelId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Step entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String memo = entity.getMemo();
        if (memo != null) {
            stmt.bindString(3, memo);
        }
 
        String startDate = entity.getStartDate();
        if (startDate != null) {
            stmt.bindString(4, startDate);
        }
 
        String endDate = entity.getEndDate();
        if (endDate != null) {
            stmt.bindString(5, endDate);
        }
        stmt.bindDouble(6, entity.getLatitude());
        stmt.bindLong(7, entity.getLongitude());
 
        byte[] image = entity.getImage();
        if (image != null) {
            stmt.bindBlob(8, image);
        }
 
        String stepTravelId = entity.getStepTravelId();
        if (stepTravelId != null) {
            stmt.bindString(9, stepTravelId);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public Step readEntity(Cursor cursor, int offset) {
        Step entity = new Step( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // memo
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // startDate
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // endDate
            cursor.getFloat(offset + 5), // latitude
            cursor.getInt(offset + 6), // longitude
            cursor.isNull(offset + 7) ? null : cursor.getBlob(offset + 7), // image
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // stepTravelId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Step entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMemo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStartDate(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setEndDate(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLatitude(cursor.getFloat(offset + 5));
        entity.setLongitude(cursor.getInt(offset + 6));
        entity.setImage(cursor.isNull(offset + 7) ? null : cursor.getBlob(offset + 7));
        entity.setStepTravelId(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Step entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(Step entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Step entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "stepList" to-many relationship of Travel. */
    public List<Step> _queryTravel_StepList(String stepTravelId) {
        synchronized (this) {
            if (travel_StepListQuery == null) {
                QueryBuilder<Step> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.StepTravelId.eq(null));
                travel_StepListQuery = queryBuilder.build();
            }
        }
        Query<Step> query = travel_StepListQuery.forCurrentThread();
        query.setParameter(0, stepTravelId);
        return query.list();
    }

}
